# This file contains the configuration for the test suite

# ADES configuration options
# Default values are for the demo platform
# Change these values to run the test suite on a different platform

base_domain: "192-168-49-2.nip.io"
#base_domain: "demo.eoepca.org"
platform_domain: "auth.demo.eoepca.org"
base_url: "http://auth.192-168-49-2.nip.io"
USER_NAME: "eric"
USER_PASSWORD: "defaultPWD"
workspace_prefix: "demo-user"
S3_ENDPOINT: "http://minio.demo.eoepca.org"
components:
  - ades
  - resource_catalogue
  - data_access_services
  - login_service
  - workspace

